name: http_sync
description: >
  Extremely powerful, reactive NoSQL database with
  typo-tolerant full-text search and declarative queries.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.75.3
  freezed_annotation: ^2.2.0

  # TODO https://github.com/fzyzcjy/flutter_rust_bridge/issues/1147
  uuid: any

dev_dependencies:
  build_runner: ^2.3.2
  ffigen: ^7.2.0
  freezed: ^2.2.1
  test: ^1.22.0
